### ISSUE TITLE
Dependency noble has problem in Mac os 

### ISSUE THREAD

**Issue by 404noahfound** [asednev/govee-bt-client#11]
https://github.com/asednev/govee-bt-client/blob/9c46b04a18bf7f83c5285a5a2177987b0cd1b0a2/package.json#L31
Noble is having a issue with Mac os for version 1.9.2-12. Could you update the dependency to use exactly 1.9.2-11?

**Comment by asednev** [comment]
@404noahfound happy to do that. Could you expand on issues with Noble on macOS?

**Comment by asednev** [comment]
Fixed in https://github.com/asednev/govee-bt-client/releases/tag/1.0.11
